---
# GitHub Action workflow enforcing our code style.
name: Setup Project
on:
  workflow_dispatch:
    inputs:
      target_path:
        description: Path of the python project to lint
        required: true
# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: setup-${{ github.sha }}
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: '3.12'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: python -m pip install poetry==1.8.3
      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.target_path
          }}
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/${{ github.event.inputs.target_path }}/.venv
          key: ${{ runner.os }}-venv-${{ github.event.inputs.target_path }}-${{ hashFiles('**/poetry.lock')
            }}
      - name: Install dependencies
        run: python -m poetry install
        working-directory: ${{ github.workspace }}/${{ github.event.inputs.target_path
          }}
