---
# GitHub Action workflow enforcing our code style.
name: Setup Project
on:
  workflow_dispatch:
    inputs:
      target_path:
        description: Path of the python project to lint
        required: true
      python_version:
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install poetry
        run: python -m pip install poetry==1.8.3
      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true
        working-directory: ./${{ inputs.target_path}}
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: ./${{ github.event.inputs.target_path }}/.venv
          key: venv-${{ inputs.target_path }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: python -m poetry install
        working-directory: ./${{ inputs.target_path }}
