---
name: Lint
# Trigger the workflow on both push (to the main repository, on the main branch)
# and pull requests (against the main repository, but from any repo, from any branch).
on:
  push:
  pull_request:
# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
env:
  PYTHON_VERSION: '3.12'
concurrency: setup-${{ github.sha }}
jobs:
  setup-projects:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [bot, api]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: python -m pip install poetry==1.8.3
      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true

      # TODO: Add caching for dependencies
      - name: Install dependencies for ${{ matrix.folder }}
        run: |
          python -m poetry install
        working-directory: ./${{ matrix.folder }}
      - name: Upload virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: venv-${{ matrix.folder }}
          path: ${{ matrix.folder }}/.venv
  lint:
    runs-on: ubuntu-latest
    needs: setup-projects
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download virtual environments
        uses: actions/download-artifact@v4
        with:
          path: venvs
      - name: Move venvs to correct locations
        run: |
          for venv in venvs/*; do
            project=$(basename $venv | sed 's/^venv-//')
            echo "Moving venv for $project to its original directory"
            mv $venv $project/.venv
          done
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
