---
name: Lint All
# Trigger the workflow on both push (to the main repository, on the main branch)
# and pull requests (against the main repository, but from any repo, from any branch).
on:
  push:
    branches: [main, beta]
  pull_request:
# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.
concurrency: setup-${{ github.sha }}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [bot, api]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup {{ matrix.folder }}
        uses: ./.github/workflows/setup
        with:
          target_folder: ${{ matrix.folder }}
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
